### ISSUE TITLE
v1.5.0-beta.3 Linux server crashes when restarting

### ISSUE THREAD

**Issue by Brazzabro** [CS-NextClient/NextClientServerApi#3]
v1.5.0-beta.3 Linux server crashes when restarting
```
Program terminated with signal SIGABRT, Aborted.
#0  0xf7f43d99 in __kernel_vsyscall ()
#0  0xf7f43d99 in __kernel_vsyscall ()
#1  0xf7a95416 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7a7d3f7 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf7ada41c in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf7ae26cf in ?? () from /lib/i386-linux-gnu/libc.so.6
#5  0xf7ae458d in ?? () from /lib/i386-linux-gnu/libc.so.6
#6  0xf06f1840 in operator delete(void*) () from cstrike/addons/amxmodx/modules/nextclientapi_amxx_i386.so
#7  0xf06e7dc0 in EventManager::~EventManager() () from cstrike/addons/amxmodx/modules/nextclientapi_amxx_i386.so
#8  0xf06e8cc0 in NextClientApi::~NextClientApi() () from cstrike/addons/amxmodx/modules/nextclientapi_amxx_i386.so
#9  0xf06e7bd2 in EventManager::~EventManager() () from cstrike/addons/amxmodx/modules/nextclientapi_amxx_i386.so
#10 0xf06e8cc0 in NextClientApi::~NextClientApi() () from cstrike/addons/amxmodx/modules/nextclientapi_amxx_i386.so
#11 0xf7a97f06 in ?? () from /lib/i386-linux-gnu/libc.so.6
#12 0xf7a980e7 in exit () from /lib/i386-linux-gnu/libc.so.6
#13 0xf7a7eee1 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#14 0x080493a1 in _start ()
No symbol table info available.
```
ReHLDS version: 3.13.0.823-dev
ReGameDLL version: 5.26.0.668-dev
Metamod-r v1.3.0.150
AMX Mod X v1.10.0.5461

**Comment by Polarhigh** [comment]
fixed in 7a78665
